---
- name: Add tags
  hosts: localhost
  tasks:
    - name: Add gce_tag to reddit-app
      gce_tag:
        zone: europe-west1-b
        project_id: steadfast-slate-219116
        instance_name: reddit-app
        tags: app
        state: present

    - name: Add gce_tag to reddit-db
      gce_tag:
        zone: europe-west1-b
        project_id: steadfast-slate-219116
        instance_name: reddit-db
        tags: db
        state: present