---
- name: App configuration
  hosts: reddit-app
  become: true
  vars:
    db_host: 10.132.0.2
  tasks:
    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: restart puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: Enable puma
      become: true
      systemd: name=puma enabled=yes

  handlers:  
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
